USE INVESTIMENTO

GO

CREATE TABLE ATIVO
(
	COD_ATIVO INT IDENTITY NOT NULL,
	NOM_SIMBOLO VARCHAR(20) NOT NULL,
	NOM_ATIVO VARCHAR(100) NOT NULL,	
	VAL_QUANTIDADE_DISPONIVEL INT NOT NULL,
	VAL_PRECO DECIMAL(18,2) NOT NULL,
	VAL_MERCADO DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_ATIVO PRIMARY KEY(COD_ATIVO)
); 

CREATE UNIQUE INDEX UQ_ATIVO_01 ON ATIVO(NOM_SIMBOLO)

INSERT ATIVO(NOM_SIMBOLO, NOM_ATIVO, VAL_QUANTIDADE_DISPONIVEL, VAL_PRECO) VALUES('ALPA4', 'ALPARGATAS', 2, 9.07)

CREATE TABLE CLIENTE
(
	COD_CLIENTE INT IDENTITY NOT NULL,
	NOM_CLIENTE VARCHAR(100) NOT NULL,
	NOM_EMAIL VARCHAR(50) NOT NULL,
	NOM_SENHA VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(COD_CLIENTE)
); 

CREATE UNIQUE INDEX UQ_CLIENTE_01 ON CLIENTE(NOM_EMAIL)

CREATE TABLE CONTA
(
	COD_CONTA INT IDENTITY NOT NULL,
	COD_CLIENTE INT NOT NULL,
	VAL_SALDO DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_CONTA PRIMARY KEY(COD_CONTA),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE),
); 