USE INVESTIMENTO

GO

CREATE TABLE ATIVO
(
	COD_ATIVO INT IDENTITY NOT NULL,
	NOM_SIMBOLO VARCHAR(20) NOT NULL,
	NOM_ATIVO VARCHAR(100) NOT NULL,	
	VAL_QUANTIDADE_DISPONIVEL INT NOT NULL,
	VAL_PRECO DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_ATIVO PRIMARY KEY(COD_ATIVO)
); 

CREATE UNIQUE INDEX UQ_ATIVO_01 ON ATIVO(NOM_SIMBOLO)

INSERT ATIVO(NOM_SIMBOLO, NOM_ATIVO, VAL_QUANTIDADE_DISPONIVEL, VAL_PRECO) VALUES('ALPA4', 'ALPARGATAS', 2, 9.07)