USE INVESTIMENTO

GO

CREATE TABLE ATIVO
(
	COD_ATIVO INT IDENTITY NOT NULL,
	NOM_SIMBOLO VARCHAR(20) NOT NULL,
	NOM_ATIVO VARCHAR(100) NOT NULL,	
	VAL_QUANTIDADE_DISPONIVEL INT NOT NULL,
	VAL_PRECO DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_ATIVO PRIMARY KEY(COD_ATIVO)
); 

CREATE UNIQUE INDEX UQ_ATIVO_01 ON ATIVO(NOM_SIMBOLO)

CREATE TABLE CLIENTE
(
	COD_CLIENTE INT IDENTITY NOT NULL,
	NOM_CLIENTE VARCHAR(100) NOT NULL,
	NOM_EMAIL VARCHAR(50) NOT NULL,
	NOM_SENHA VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(COD_CLIENTE)
); 

CREATE UNIQUE INDEX UQ_CLIENTE_01 ON CLIENTE(NOM_EMAIL)

CREATE TABLE CONTA
(
	COD_CONTA INT IDENTITY NOT NULL,
	COD_CLIENTE INT NOT NULL,
	VAL_SALDO DECIMAL(18,2) NOT NULL,
	DAT_INC DATETIME2 NOT NULL,
	DAT_ALT DATETIME2 NOT NULL,	
	CONSTRAINT PK_CONTA PRIMARY KEY (COD_CONTA),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE),
); 

CREATE TABLE TRANSACAO_CONTA
(
	COD_TRANSACAO_CONTA INT IDENTITY NOT NULL,
	COD_CONTA INT NOT NULL,
	COD_TIPO_TRANSACAO INT NOT NULL,
	VAL_TRANSACAO DECIMAL(18,2) NOT NULL,
	DAT_INC DATETIME2 NOT NULL,
	CONSTRAINT PK_TRANSACAO_CONTA PRIMARY KEY (COD_TRANSACAO_CONTA),
	CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (COD_CONTA) REFERENCES CONTA (COD_CONTA),
); 


CREATE TABLE TRANSACAO_INVESTIMENTO
(
	COD_TRANSACAO_INVESTIMENTO INT IDENTITY NOT NULL,
	COD_CONTA INT NOT NULL,
	COD_ATIVO INT NOT NULL,
	COD_TIPO_TRANSACAO INT NOT NULL,
	VAL_QUANTIDADE INT NOT NULL,
	VAL_PRECO DECIMAL(18,2) NOT NULL,	
	DAT_INC DATETIME2 NOT NULL,
	CONSTRAINT PK_TRANSACAO_INVESTIMENTO PRIMARY KEY (COD_TRANSACAO_INVESTIMENTO),
	CONSTRAINT FK_TRANSACAO_INVESTIMENTO_CONTA FOREIGN KEY (COD_CONTA) REFERENCES CONTA (COD_CONTA),
	CONSTRAINT FK_TRANSACAO_INVESTIMENTO_ATIVO FOREIGN KEY (COD_ATIVO) REFERENCES ATIVO (COD_ATIVO),
); 


SELECT * FROM ATIVO
SELECT * FROM CLIENTE
SELECT * FROM CONTA
SELECT * FROM TRANSACAO_CONTA
SELECT * FROM TRANSACAO_INVESTIMENTO